### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by purp0s3**
Perhaps made it look cleaner and better formatted. Merge if you wish, just experimenting and learning :).

### CODE REVIEW

**Comment by c22dev** [comment]
hey, thanks for push request. Am I allowed to copy paste (without merging) this in my readme ? Credit will be given to you.

**Comment by purp0s3** [comment]
yea, but, why..

**Comment by c22dev** [comment]
cause contributors section

**Comment by c22dev** [comment]
update you're pull request to the new readme and I'll merge it

**Pull request closed without merging**
